// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1kImSwPPkbXUP2HNDSPq394hf4GFtex4',
    appId: '1:73523727835:web:b1ba4abe97f712fafbabfe',
    messagingSenderId: '73523727835',
    projectId: 'buenamama-6c27b',
    authDomain: 'buenamama-6c27b.firebaseapp.com',
    databaseURL: 'https://buenamama-6c27b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buenamama-6c27b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-gjm_-evBlW6pyNMGggsnWETvaQ-8-SM',
    appId: '1:73523727835:android:1afb20a2f01f1f3dfbabfe',
    messagingSenderId: '73523727835',
    projectId: 'buenamama-6c27b',
    databaseURL: 'https://buenamama-6c27b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buenamama-6c27b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd-_5Cp_18BrlrSUGo-JbvyC6HwpFDo0E',
    appId: '1:73523727835:ios:83a080ef6fb88e67fbabfe',
    messagingSenderId: '73523727835',
    projectId: 'buenamama-6c27b',
    databaseURL: 'https://buenamama-6c27b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buenamama-6c27b.firebasestorage.app',
    iosBundleId: 'com.example.buenamama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd-_5Cp_18BrlrSUGo-JbvyC6HwpFDo0E',
    appId: '1:73523727835:ios:83a080ef6fb88e67fbabfe',
    messagingSenderId: '73523727835',
    projectId: 'buenamama-6c27b',
    databaseURL: 'https://buenamama-6c27b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buenamama-6c27b.firebasestorage.app',
    iosBundleId: 'com.example.buenamama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1kImSwPPkbXUP2HNDSPq394hf4GFtex4',
    appId: '1:73523727835:web:c187ad5cd9444ad2fbabfe',
    messagingSenderId: '73523727835',
    projectId: 'buenamama-6c27b',
    authDomain: 'buenamama-6c27b.firebaseapp.com',
    databaseURL: 'https://buenamama-6c27b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buenamama-6c27b.firebasestorage.app',
  );
}
